// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu7xaGxemb3BvvYU3IVQW8rrU2cwdXaSY',
    appId: '1:84338375131:web:11e1668c85c1a50c390ffe',
    messagingSenderId: '84338375131',
    projectId: 'quizapp-bf1d1',
    authDomain: 'quizapp-bf1d1.firebaseapp.com',
    storageBucket: 'quizapp-bf1d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbGxKUgGGxWDRfXzIRFd3FZ85y2hN1TYc',
    appId: '1:84338375131:android:57390ad8e1e73053390ffe',
    messagingSenderId: '84338375131',
    projectId: 'quizapp-bf1d1',
    storageBucket: 'quizapp-bf1d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZsHCVO0mYF-U1fSnjH_Y7OAF1yLdPJAY',
    appId: '1:84338375131:ios:5b91b4c29ec6830d390ffe',
    messagingSenderId: '84338375131',
    projectId: 'quizapp-bf1d1',
    storageBucket: 'quizapp-bf1d1.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZsHCVO0mYF-U1fSnjH_Y7OAF1yLdPJAY',
    appId: '1:84338375131:ios:5b91b4c29ec6830d390ffe',
    messagingSenderId: '84338375131',
    projectId: 'quizapp-bf1d1',
    storageBucket: 'quizapp-bf1d1.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu7xaGxemb3BvvYU3IVQW8rrU2cwdXaSY',
    appId: '1:84338375131:web:127337b80e445fbf390ffe',
    messagingSenderId: '84338375131',
    projectId: 'quizapp-bf1d1',
    authDomain: 'quizapp-bf1d1.firebaseapp.com',
    storageBucket: 'quizapp-bf1d1.firebasestorage.app',
  );
}
